import {
  PublicKey,
  SYSVAR_CLOCK_PUBKEY,
  TransactionInstruction,
} from "@solana/web3.js";
import type { RiskPolicyDecision } from "@perps-risk/cross-venue";

export const RISK_VAULT_PROGRAM_ID = new PublicKey(
  "33fMx1DC1XXdSYXG8VUFqH5y1gDqxmEpbTTwESx21Rtq",
);
export const VAULT_SEED = Buffer.from("vault");
export const RISK_STATE_SEED = Buffer.from("risk_state");

const VAULT_DISCRIMINATOR = Buffer.from([211, 8, 232, 43, 2, 152, 117, 119]);
const RISK_STATE_DISCRIMINATOR = Buffer.from([
  120, 33, 58, 236, 210, 191, 106, 97,
]);
// Generated by Anchor for global:update_risk_state in the current program IDL.
const UPDATE_RISK_STATE_DISCRIMINATOR = Buffer.from([
  71, 227, 24, 202, 12, 22, 17, 96,
]);

export type OnChainRiskLevel = "low" | "medium" | "high" | "critical";
export type OnChainContagionState =
  "NONE" | "ISOLATED" | "DEVELOPING" | "ACTIVE";

export interface RiskStateCommand extends RiskPolicyDecision {
  nonce: bigint;
}

export interface RiskStateSnapshot {
  riskLevel: OnChainRiskLevel;
  riskScore: number;
  contagionState: OnChainContagionState;
  maxLeverageX100: number;
  observedAt: number;
  updatedAt: number;
  nonce: bigint;
  bump: number;
}

const riskLevelOrdinal: Record<OnChainRiskLevel, number> = {
  low: 0,
  medium: 1,
  high: 2,
  critical: 3,
};
const contagionOrdinal: Record<OnChainContagionState, number> = {
  NONE: 0,
  ISOLATED: 1,
  DEVELOPING: 2,
  ACTIVE: 3,
};
const ordinalRiskLevel: OnChainRiskLevel[] = [
  "low",
  "medium",
  "high",
  "critical",
];
const ordinalContagion: OnChainContagionState[] = [
  "NONE",
  "ISOLATED",
  "DEVELOPING",
  "ACTIVE",
];

export function deriveVaultAddress(
  collateralMint: PublicKey,
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [VAULT_SEED, collateralMint.toBuffer()],
    RISK_VAULT_PROGRAM_ID,
  );
}

export function deriveRiskStateAddress(vault: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [RISK_STATE_SEED, vault.toBuffer()],
    RISK_VAULT_PROGRAM_ID,
  );
}

function assertI64(value: number, label: string): void {
  if (!Number.isSafeInteger(value) || value < 0) {
    throw new Error(
      `${label} must be a nonnegative safe integer timestamp in seconds`,
    );
  }
}

function assertPolicy(decision: RiskPolicyDecision): void {
  assertI64(decision.observedAt, "observedAt");
  if (
    !Number.isInteger(decision.riskScore) ||
    decision.riskScore < 0 ||
    decision.riskScore > 100
  ) {
    throw new Error("riskScore must be an integer from 0 through 100");
  }
  if (
    !Number.isInteger(decision.maxLeverageX100) ||
    decision.maxLeverageX100 < 0 ||
    decision.maxLeverageX100 > 300
  ) {
    throw new Error("maxLeverageX100 must be an integer from 0 through 300");
  }
  if (
    !Object.hasOwn(riskLevelOrdinal, decision.riskLevel) ||
    !Object.hasOwn(contagionOrdinal, decision.contagionState)
  ) {
    throw new Error("Risk level or contagion state is invalid");
  }
  const scoreRange: Record<OnChainRiskLevel, [number, number]> = {
    low: [0, 25],
    medium: [26, 50],
    high: [51, 75],
    critical: [76, 100],
  };
  const [minScore, maxScore] = scoreRange[decision.riskLevel];
  if (decision.riskScore < minScore || decision.riskScore > maxScore) {
    throw new Error("riskScore does not match its riskLevel");
  }
  const levelCap: Record<OnChainRiskLevel, number> = {
    low: 300,
    medium: 200,
    high: 100,
    critical: 0,
  };
  const contagionCap: Record<OnChainContagionState, number> = {
    NONE: 300,
    ISOLATED: 300,
    DEVELOPING: 100,
    ACTIVE: 0,
  };
  if (
    decision.maxLeverageX100 >
    Math.min(
      levelCap[decision.riskLevel],
      contagionCap[decision.contagionState],
    )
  ) {
    throw new Error(
      "maxLeverageX100 exceeds the configured risk/contagion policy cap",
    );
  }
}

export function encodeUpdateRiskState(command: RiskStateCommand): Buffer {
  assertPolicy(command);
  if (command.nonce <= 0n || command.nonce > 0xffff_ffff_ffff_ffffn) {
    throw new Error("nonce must fit in a nonzero u64");
  }
  const data = Buffer.alloc(29);
  UPDATE_RISK_STATE_DISCRIMINATOR.copy(data, 0);
  data.writeUInt8(riskLevelOrdinal[command.riskLevel], 8);
  data.writeUInt8(command.riskScore, 9);
  data.writeUInt8(contagionOrdinal[command.contagionState], 10);
  data.writeUInt16LE(command.maxLeverageX100, 11);
  data.writeBigInt64LE(BigInt(command.observedAt), 13);
  data.writeBigUInt64LE(command.nonce, 21);
  return data;
}

export function buildUpdateRiskStateInstruction(
  vault: PublicKey,
  riskAuthority: PublicKey,
  command: RiskStateCommand,
): TransactionInstruction {
  const [riskState] = deriveRiskStateAddress(vault);
  return new TransactionInstruction({
    programId: RISK_VAULT_PROGRAM_ID,
    keys: [
      { pubkey: riskAuthority, isSigner: true, isWritable: false },
      { pubkey: vault, isSigner: false, isWritable: false },
      { pubkey: riskState, isSigner: false, isWritable: true },
      { pubkey: SYSVAR_CLOCK_PUBKEY, isSigner: false, isWritable: false },
    ],
    data: encodeUpdateRiskState(command),
  });
}

export function decodeVaultIdentity(data: Buffer | Uint8Array): {
  riskAuthority: PublicKey;
  collateralMint: PublicKey;
  bump: number;
} {
  const bytes = Buffer.from(data);
  if (bytes.length < 121 || !bytes.subarray(0, 8).equals(VAULT_DISCRIMINATOR)) {
    throw new Error(
      "Vault account has an invalid owner layout or discriminator",
    );
  }
  return {
    riskAuthority: new PublicKey(bytes.subarray(40, 72)),
    collateralMint: new PublicKey(bytes.subarray(72, 104)),
    bump: bytes.readUInt8(120),
  };
}

export function decodeRiskState(data: Buffer | Uint8Array): RiskStateSnapshot {
  const bytes = Buffer.from(data);
  if (
    bytes.length < 38 ||
    !bytes.subarray(0, 8).equals(RISK_STATE_DISCRIMINATOR)
  ) {
    throw new Error("RiskState account has an invalid layout or discriminator");
  }
  const riskLevel = ordinalRiskLevel[bytes.readUInt8(8)];
  const contagionState = ordinalContagion[bytes.readUInt8(10)];
  if (!riskLevel || !contagionState)
    throw new Error("RiskState contains an invalid enum value");
  const observedAt = Number(bytes.readBigInt64LE(13));
  const updatedAt = Number(bytes.readBigInt64LE(21));
  if (!Number.isSafeInteger(observedAt) || !Number.isSafeInteger(updatedAt)) {
    throw new Error("RiskState contains an unsupported timestamp");
  }
  const riskScore = bytes.readUInt8(9);
  const maxLeverageX100 = bytes.readUInt16LE(11);
  if (
    observedAt < 0 ||
    updatedAt < 0 ||
    riskScore > 100 ||
    maxLeverageX100 > 300
  ) {
    throw new Error(
      "RiskState contains an invalid timestamp, score, or leverage cap",
    );
  }
  const scoreRange: Record<OnChainRiskLevel, [number, number]> = {
    low: [0, 25],
    medium: [26, 50],
    high: [51, 75],
    critical: [76, 100],
  };
  const [minimumScore, maximumScore] = scoreRange[riskLevel];
  const maxAllowedLeverage = Math.min(
    { low: 300, medium: 200, high: 100, critical: 0 }[riskLevel],
    { NONE: 300, ISOLATED: 300, DEVELOPING: 100, ACTIVE: 0 }[contagionState],
  );
  if (
    riskScore < minimumScore ||
    riskScore > maximumScore ||
    maxLeverageX100 > maxAllowedLeverage
  ) {
    throw new Error(
      "RiskState contains a policy inconsistent with its score or contagion",
    );
  }
  return {
    riskLevel,
    riskScore,
    contagionState,
    maxLeverageX100,
    observedAt,
    updatedAt,
    nonce: bytes.readBigUInt64LE(29),
    bump: bytes.readUInt8(37),
  };
}

export function riskStateMatchesDecision(
  state: RiskStateSnapshot,
  decision: RiskPolicyDecision,
): boolean {
  return (
    state.riskLevel === decision.riskLevel &&
    state.riskScore === decision.riskScore &&
    state.contagionState === decision.contagionState &&
    state.maxLeverageX100 === decision.maxLeverageX100 &&
    state.observedAt === decision.observedAt
  );
}
